origincert: /srv/www/fajarmandiri.store/config/cert.pem
tunnel: kasir
credentials-file: /srv/www/fajarmandiri.store/config/7dfdc496-a179-4074-8baa-9d6a9c5a59ec.json

ingress:
  - hostname: hutang.fajarmandiri.store
    service: http://localhost:4003 # Catatan Hutang
  - hostname: pelayanan.fajarmandiri.store
    service: http://localhost:4002   # Pelayanan Service
  - hostname: chat.fajarmandiri.store
    service: http://localhost:6000   # Django tetap
  - hostname: fj-server.fajarmandiri.store
    service: ssh://localhost:22   # ssh server
  - hostname: kasir.fajarmandiri.store
    service: http://localhost:4001   # kasir port baru
  - hostname: fajarmandiri.store
    service: http://localhost:4000   # web utama port baru
  - service: http_status:404
